# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        compiler: [GCC-13, LLVM-Clang-16, LLVM-Clang-17]
        test_with: [Headers, Module]
        build_type: [Debug, Release]

        exclude:
          - compiler: GCC-13
            test_with: Module
          - compiler: LLVM-Clang-16
            test_with: Module

        include:
          - compiler: GCC-13
            cxx: g++-13
            install: |
              brew update
              brew install gcc@13 ninja
          - compiler: LLVM-Clang-16
            cxx: $(brew --prefix llvm@16)/bin/clang++
            install: |
              brew install llvm@16 ninja
          - compiler: LLVM-Clang-17
            cxx: $(brew --prefix llvm@17)/bin/clang++
            install: |
              brew install llvm@17 ninja


    steps:
    - uses: actions/checkout@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
               -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
               -DFLUX_BUILD_MODULE=${{matrix.test_with == 'Module'}} \
               -DFLUX_BUILD_TESTS_USING_MODULE=${{matrix.test_with == 'Module'}} \
               $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
